[theme]
# The preset Streamlit theme that your custom theme inherits from.
# Can be "light" or "dark".
base="light"

# Primary accent color for interactive elements.
primaryColor="#484848ff"

# Background color for the main content area.
backgroundColor="#fafafa"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#eee"

# Color used for almost all text.
textColor="#000000"

# Font family for all text in the app.
font="sans serif"